org.gradle.jvmargs=-Xmx3G -Dfile.encoding=GBK
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
geckolib_version=4.8.4
langchain4j_version=1.18.1
langchain4j_skills_version=1.18.1-beta28

mod_id=wishing_willow
mod_name=Wishing Willow
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.ikunkk02.wishingwillow
mod_authors=ikunkk02-afk
mod_description=A mysterious Forge mod centered on the Wishing Willow.
