package com.ikunkk02.wishingwillow.execution;

import com.ikunkk02.wishingwillow.WishingWillow;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.Tag;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.boss.wither.WitherBoss;
import net.minecraft.world.phys.Vec3;
import javax.annotation.Nullable;
import java.util.*;

/** Bounded persisted literalization of the absurd "never alone" wish. */
public final class NeverAloneSavedData extends net.minecraft.world.level.saveddata.SavedData {
    private static final String DATA_NAME="wishing_willow_never_alone";
    private final Map<UUID,NeverAloneRule> rules=new LinkedHashMap<>();
    public static NeverAloneSavedData get(MinecraftServer s){return s.overworld().getDataStorage().computeIfAbsent(NeverAloneSavedData::load,NeverAloneSavedData::new,DATA_NAME);}
    public void add(ServerPlayer owner,String session,long now){NeverAloneRule r=new NeverAloneRule(owner.getUUID(),session,WishExecutionConfig.NEVER_ALONE_INITIAL_COUNT.get(),WishExecutionConfig.NEVER_ALONE_MINIMUM_COUNT.get(),WishExecutionConfig.NEVER_ALONE_TARGET_COUNT.get(),WishExecutionConfig.NEVER_ALONE_SEARCH_RADIUS.get(),WishExecutionConfig.NEVER_ALONE_TELEPORT_DISTANCE.get(),WishExecutionConfig.NEVER_ALONE_REFILL_INTERVAL.get(),1.5,6,true,now);rules.put(owner.getUUID(),r);int added=refill(owner,r,r.initial);r.next=now+r.interval;setDirty();WishingWillow.LOGGER.info("Never alone rule created owner={} initialCompanions={} targetCompanions={}",owner.getUUID(),added,r.target);}
    @Nullable public NeverAloneRule find(UUID owner){return rules.get(owner);}
    public void tick(MinecraftServer s,long now){if(now%10!=0)return;for(NeverAloneRule r:rules.values()){ServerPlayer owner=s.getPlayerList().getPlayer(r.owner);if(owner==null)continue;int current=maintain(owner,r);if(now>=r.next&&current<r.min){int added=refill(owner,r,r.target-current);r.next=now+r.interval;setDirty();WishingWillow.LOGGER.info("Never alone refill owner={} current={} added={} target={}",owner.getUUID(),current,added,r.target);}}}
    private int maintain(ServerPlayer owner,NeverAloneRule r){int current=0;for(Iterator<UUID> it=r.companions.iterator();it.hasNext();){Entity e=owner.serverLevel().getEntity(it.next());if(!(e instanceof LivingEntity l)||!l.isAlive()){it.remove();continue;}current++;double d=l.distanceTo(owner);if(d>r.teleport){Vec3 p=SafeSpawnPositionFinder.find(owner.serverLevel(),l,owner.position(),3,12,false,owner.getYRot(),l.getUUID().getLeastSignificantBits());if(p!=null){l.teleportTo(p.x,p.y,p.z);WishingWillow.LOGGER.info("Never alone companion teleported entity={} distance={}",l.getUUID(),(int)d);}}if(l instanceof Mob m&&d>r.follow)m.getNavigation().moveTo(owner,r.speed);}return current;}
    private int refill(ServerPlayer owner,NeverAloneRule r,int wanted){if(wanted<=0)return 0;ServerLevel level=owner.serverLevel();List<LivingEntity> values=level.getEntitiesOfClass(LivingEntity.class,owner.getBoundingBox().inflate(r.radius),e->eligible(e,owner)&&!r.companions.contains(e.getUUID()));values.sort(Comparator.comparingDouble(owner::distanceToSqr));int added=0;for(LivingEntity l:values){if(added>=wanted||r.companions.size()>=r.target)break;Vec3 p=SafeSpawnPositionFinder.find(level,l,owner.position(),3,12,false,owner.getYRot(),l.getUUID().getLeastSignificantBits());if(p==null)continue;l.teleportTo(p.x,p.y,p.z);r.companions.add(l.getUUID());if(l instanceof Mob m)m.getNavigation().moveTo(owner,r.speed);added++;WishingWillow.LOGGER.info("Never alone companion added owner={} entity={} uuid={}",owner.getUUID(),l.getType(),l.getUUID());}return added;}
    private static boolean eligible(LivingEntity e,ServerPlayer owner){return e!=owner&&!(e instanceof ServerPlayer)&&!(e instanceof EnderDragon)&&!(e instanceof WitherBoss)&&!e.isPassenger()&&e.level()==owner.level();}
    @Override public CompoundTag save(CompoundTag tag){ListTag list=new ListTag();rules.values().forEach(r->list.add(r.toNbt()));tag.put("Rules",list);return tag;}
    private static NeverAloneSavedData load(CompoundTag tag){NeverAloneSavedData d=new NeverAloneSavedData();for(Tag v:tag.getList("Rules",Tag.TAG_COMPOUND)){NeverAloneRule r=NeverAloneRule.fromNbt((CompoundTag)v);if(r!=null)d.rules.put(r.owner,r);}return d;}
    public static final class NeverAloneRule {private final UUID owner;private final String session;private final int initial,min,target,radius,teleport,interval;private final double speed,follow;private final boolean permanent;private final long created;private long next;private final Set<UUID> companions=new LinkedHashSet<>();public NeverAloneRule(UUID owner,String session,int initial,int min,int target,int radius,int teleport,int interval,double speed,double follow,boolean permanent,long created){this.owner=owner;this.session=session;this.initial=initial;this.min=min;this.target=target;this.radius=radius;this.teleport=teleport;this.interval=interval;this.speed=speed;this.follow=follow;this.permanent=permanent;this.created=created;}public UUID ownerId(){return owner;}public int initialCompanions(){return initial;}public int minimumCompanions(){return min;}public int targetCompanions(){return target;}public int searchRadius(){return radius;}public int teleportDistance(){return teleport;}public int refillInterval(){return interval;}public boolean permanent(){return permanent;}CompoundTag toNbt(){CompoundTag t=new CompoundTag();t.putUUID("Owner",owner);t.putString("Session",session);t.putInt("Initial",initial);t.putInt("Min",min);t.putInt("Target",target);t.putInt("Radius",radius);t.putInt("Teleport",teleport);t.putInt("Interval",interval);t.putDouble("Speed",speed);t.putDouble("Follow",follow);t.putBoolean("Permanent",permanent);t.putLong("Created",created);t.putLong("Next",next);ListTag ids=new ListTag();companions.forEach(id->ids.add(net.minecraft.nbt.StringTag.valueOf(id.toString())));t.put("Companions",ids);return t;}@Nullable static NeverAloneRule fromNbt(CompoundTag t){if(!t.hasUUID("Owner"))return null;NeverAloneRule r=new NeverAloneRule(t.getUUID("Owner"),t.getString("Session"),t.getInt("Initial"),t.getInt("Min"),t.getInt("Target"),t.getInt("Radius"),t.getInt("Teleport"),t.getInt("Interval"),t.getDouble("Speed"),t.getDouble("Follow"),t.getBoolean("Permanent"),t.getLong("Created"));r.next=t.getLong("Next");for(Tag v:t.getList("Companions",Tag.TAG_STRING))try{r.companions.add(UUID.fromString(v.getAsString()));}catch(IllegalArgumentException ignored){}return r;}}
}