package com.ikunkk02.wishingwillow.ai;

public enum AiErrorCategory {
    NONE,
    NOT_CONFIGURED,
    UNAUTHORIZED,
    FORBIDDEN,
    ENDPOINT_NOT_FOUND,
    MODEL_UNAVAILABLE,
    RATE_LIMITED,
    SERVER_ERROR,
    TIMEOUT,
    DNS_FAILURE,
    CONNECTION_REFUSED,
    RESPONSE_TOO_LARGE,
    EMPTY_RESPONSE,
    MALFORMED_RESPONSE,
    UNSUPPORTED_FEATURE,
    DISCONNECTED,
    UNKNOWN
}
