package com.ikunkk02.wishingwillow.planning;

public enum WishActionType {
    GIVE_ITEM, REMOVE_ITEM, SPAWN_ENTITY, DESPAWN_ENTITY,
    APPLY_EFFECT, REMOVE_EFFECT, CLEAR_EFFECTS, APPLY_EFFECT_CATEGORY,
    TELEPORT, CHANGE_TIME, CHANGE_WEATHER,
    PLAY_SOUND, SPAWN_PARTICLE, LIGHTNING, EXPLOSION, CHANGE_BLOCK, REPLACE_BLOCK_AREA,
    PLACE_BLOCK_PATTERN, FALLING_BLOCK_SHOWER, ITEM_RAIN, CREATE_STRUCTURE,
    MODIFY_HEALTH, MODIFY_HUNGER, MODIFY_ATTRIBUTE, CHANGE_MOB_TARGET, FOLLOW_PLAYER,
    AVOID_PLAYER, CHANGE_REPUTATION, START_PREDEFINED_EVENT
}
