package com.ikunkk02.wishingwillow.planning;

public enum WishActionType {
    GIVE_ITEM, REMOVE_ITEM, SPAWN_ENTITY, DESPAWN_ENTITY,
    APPLY_EFFECT, REMOVE_EFFECT, TELEPORT, CHANGE_TIME, CHANGE_WEATHER,
    PLAY_SOUND, SPAWN_PARTICLE, LIGHTNING, EXPLOSION, CHANGE_BLOCK, REPLACE_BLOCK_AREA,
    MODIFY_HEALTH, MODIFY_HUNGER, MODIFY_ATTRIBUTE, CHANGE_MOB_TARGET, FOLLOW_PLAYER,
    AVOID_PLAYER, CHANGE_REPUTATION, START_PREDEFINED_EVENT
}
