package com.ikunkk02.wishingwillow.planning;

public enum WishTriggerType {
    NONE, AFTER_DELAY, PLAYER_SLEEP, PLAYER_WAKE, ENTER_DIMENSION, ENTER_DARK_AREA, ENTER_CAVE,
    NIGHT_START, DAY_START, PLAYER_LOW_HEALTH, PLAYER_TURNS_AROUND, PLAYER_LOOKS_AT_ENTITY,
    ENTITY_NEARBY, PLAYER_DEATH, PLAYER_KILLS_ENTITY
}
