package com.ikunkk02.wishingwillow.planning;

public enum WishPlanError {
    NONE, AI_TIMEOUT, AI_REQUEST_FAILED, EXECUTION_DISABLED, INVALID_JSON, INVALID_CANDIDATE, INVALID_REGISTRY,
    INVALID_ACTION, INVALID_PARAMETER, BUDGET_EXCEEDED, DELIVERY_CONFLICT, MISSING_MOD,
    NO_CANDIDATES, UNSATISFIED_CAPABILITIES, DISCONNECTED, STALE_RESOURCE,
    RISK_TOO_HIGH, THIRD_PARTY_ENTITY_DISABLED, THIRD_PARTY_ENTITY_SEVERITY,
    BLOCK_MODIFICATION_DISABLED, EXPLOSIONS_DISABLED, DESTRUCTIVE_EXPLOSIONS_DISABLED,
    CROSS_DIMENSION_TELEPORT_DISABLED, DESTRUCTIVE_SEVERITY_DISABLED, DEBUG_SAFE_MODE,
    INVALID_EVENT, UNTRUSTED_REGISTRY_CANDIDATE, UNSUPPORTED_ACTION, UNKNOWN
}
