package com.ikunkk02.wishingwillow.planning;

public enum WishPlanError {
    NONE, AI_TIMEOUT, AI_REQUEST_FAILED, INVALID_JSON, INVALID_CANDIDATE, INVALID_REGISTRY,
    INVALID_ACTION, INVALID_PARAMETER, BUDGET_EXCEEDED, DELIVERY_CONFLICT, MISSING_MOD,
    NO_CANDIDATES, UNSATISFIED_CAPABILITIES, DISCONNECTED, STALE_RESOURCE, UNKNOWN
}
