package com.ikunkk02.wishingwillow.agent.core;

public enum WishAgentDebugState {
    ROUTE_SELECTED,
    DIRECT_PLANNING_STARTED,
    DIRECT_ACTION_RECEIVED,
    AGENT_STARTED,
    ITERATION_STARTED,
    TOOL_CALLED,
    TOOL_RESULT,
    FALLBACK_STARTED,
    COMPATIBILITY_STARTED,
    VALIDATION,
    COMPLETED,
    FAILED,
    CANCELLED
}
