package com.ikunkk02.wishingwillow.agent.core;

public enum WishAgentFallbackReason {
    NONE,
    TOOL_CALLING_UNSUPPORTED,
    TOOL_SUPPORT_PROBE_FAILED,
    AI_REQUEST_TIMEOUT,
    AGENT_DEADLINE_EXCEEDED,
    MALFORMED_RESPONSE,
    EMPTY_RESPONSE,
    INVALID_TOOL_ARGUMENTS,
    MODEL_RETURNED_NO_TOOL_CALL,
    TOOL_BUDGET_EXHAUSTED,
    ITERATION_BUDGET_EXHAUSTED,
    FINALIZE_NOT_CALLED,
    UNKNOWN_TOOL_LOOP,
    DUPLICATE_TOOL_LOOP,
    UNSUPPORTED_SEMANTIC,
    CONTRACT_REVIEW_TIMEOUT,
    REVIEW_TECHNICAL_FAILURE,
    AGENT_TECHNICAL_FAILURE,
    CANCELLED
}
